/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task_1;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;

public class StringUtilsTest {

	@Test
	public void testIsPositiveNumber() {
		String testData = "4.0";
		Assertions.assertTrue(StringUtils.isPositiveNumber(testData));
	}

}
