/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task_1;

import org.apache.commons.lang3.math.NumberUtils;

public class StringUtils {

	public static boolean isPositiveNumber(String str) {
		if (!NumberUtils.isCreatable(str)) {
			return false;
		}
		return Double.parseDouble(str) > 0;
	}

}
